### ISSUE TITLE
Not able to run paste

### ISSUE THREAD

**Issue by aborruso** [liquidaty/zsv#137] opened 2023-10-01 19:20 UTC
Hi,
first of all thank you for the development of this product.

I'm using zsv version 0.3.8-alpha. If I run `zsv paste 01.csv 02.csv`, I have `71522 illegal hardware instruction  zsv paste 01.csv 02.csv`.

How to use `paste`?

Thank you

**Comment by liquidaty** [comment] 2023-10-01 19:37
Could you pls attach (or if they are trivial, paste in the body of your response) 01.csv and 02.csv?

**Comment by liquidaty** [comment] 2023-10-01 19:53
Also could you try compiling from source?

**Comment by aborruso** [comment] 2023-10-01 20:17
> Could you pls attach (or if they are trivial, paste in the body of your response) 01.csv and 02.csv?

Thank you. They are only test files.

01.csv

```
date,a
1,b
2,c
3,d
```

02.csv

```
date,t
1,h
2,j
3,k
```

**Comment by aborruso** [comment] 2023-10-01 20:18
> Also could you try compiling from source?

As soon as I can, I will try. Thank you

**Comment by liquidaty** [comment] 2023-10-01 20:20
if compiling from source, possibly better to use: https://github.com/liquidaty/zsv/tree/paste-2

**Comment by liquidaty** [comment] 2023-10-30 03:08
@aborruso it appears likely that this is due to your operating system or hardware being incompatible with the binary you were using. were you able to compile from source and reproduce? Also, what hardware/os did this issue arise on?

**Comment by liquidaty** [comment] 2023-11-09 03:20
@aborruso just wanted to check in here-- if we can't replicate, I will close this issue and assume it goes away when compiling from source, though we can reopen if that turns out not to be the case

**Closed** 2023-11-09 06:21 UTC
Labels: question
